### ISSUE TITLE
Criar Caso de Uso para utilização do ChromeVox no GoogleChrome

### ISSUE THREAD

**Issue by evaldo** [evaldo/universo_picdefvisual#10]
Criar Caso de Uso para utilização do ChromeVox no GoogleChrome

**Comment by diogoataide** [comment]
Boa noite Professor, recebi seu e-mail e estarei realizando esta tarefa qualquer dúvida entrarei em contato.

Enviado do meu iPhone

**Comment by RaphaelLuz** [comment]
Construindo caso de uso.

**Comment by evaldo** [comment]
Caso de Uso Concluído com sucesso e revisado.
